import type { MenuItem } from './types';

export const menuItems: MenuItem[] = [
  // Snacks
  {
    id: '1',
    name: 'Veg Puff',
    description: 'A flaky pastry filled with a savory mix of spiced vegetables.',
    price: 25,
    category: 'Snacks',
    imageUrl: '/images/Menu/veg_puff.jpg',
    imageHint: 'veg puff',
  },
  {
    id: '2',
    name: 'Egg Puff',
    description: 'A delicious puff pastry with a boiled egg and masala filling.',
    price: 30,
    category: 'Snacks',
    imageUrl: '/images/Menu/egg_puff.jpg',
    imageHint: 'egg puff',
  },
  {
    id: '3',
    name: 'Chicken Puff',
    description: 'A crispy and flaky puff pastry with a spicy chicken filling.',
    price: 35,
    category: 'Snacks',
    imageUrl: '/images/Menu/chicken_puff.jpg',
    imageHint: 'chicken puff',
  },
  {
    id: '4',
    name: 'Veg Samosa',
    description: 'Crispy fried pastry with a savory filling of spiced potatoes and peas.',
    price: 10,
    category: 'Snacks',
    imageUrl: '/images/Menu/veg_samosa.jpg',
    imageHint: 'samosa food',
  },
  {
    id: '25',
    name: 'Paneer Samosa',
    description: 'A crispy pastry filled with spiced paneer (Indian cottage cheese).',
    price: 20,
    category: 'Snacks',
    imageUrl: '/images/Menu/panner_samosa.jpg',
    imageHint: 'paneer samosa',
  },
  {
    id: '26',
    name: 'Chicken Samosa',
    description: 'A savory pastry filled with spiced minced chicken.',
    price: 35,
    category: 'Snacks',
    imageUrl: '/images/Menu/chicken_samosa.jpg',
    imageHint: 'chicken samosa',
  },
  {
    id: '5',
    name: 'Veg Cutlet',
    description: 'A crispy breaded patty with a savory vegetable filling.',
    price: 20,
    category: 'Snacks',
    imageUrl: '/images/Menu/veg_cutlet.jpg',
    imageHint: 'veg cutlet',
  },
  {
    id: '6',
    name: 'Chicken Cutlet',
    description: 'Crispy, golden fried chicken cutlet, and crunchy on the outside.',
    price: 30,
    category: 'Snacks',
    imageUrl: '/images/Menu/chicken_cutlet.jpg',
    imageHint: 'Chicken Cutlet',
  },
  {
    id: '7',
    name: 'Medu Vada',
    description: 'Crispy, savory lentil doughnuts, soft on the inside.',
    price: 25,
    category: 'Snacks',
    imageUrl: '/images/Menu/medu_vada.jpg',
    imageHint: 'medu vada',
  },
  // Drinks
  {
    id: '9',
    name: 'Tea',
    description: 'A fragrant and spiced tea that is a staple in India.',
    price: 12,
    category: 'Drinks',
    imageUrl: '/images/Menu/tea.jpg',
    imageHint: 'masala tea',
  },
  {
    id: '10',
    name: 'Fresh Lime Soda',
    description: 'A refreshing fizzy drink available sweet, salt or mixed.',
    price: 25,
    category: 'Drinks',
    imageUrl: '/images/Menu/lemon_tea.jpg',
    imageHint: 'lime soda',
  },
  {
    id: '11',
    name: 'Coffee',
    description: 'Freshly brewed hot coffee with a rich aroma and smooth flavor.',
    price: 20,
    category: 'Drinks',
    imageUrl: '/images/Menu/coffee.jpg',
    imageHint: 'Coffee',
  },
  {
    id: '12',
    name: 'Rose Milk',
    description: 'A sweet and fragrant milk drink flavored with rose syrup.',
    price: 25,
    category: 'Drinks',
    imageUrl: '/images/Menu/rose_milk.jpg',
    imageHint: 'rose milk',
  },
  {
    id: '13',
    name: 'Badam Milk',
    description: 'A rich and creamy milk drink flavored with almonds.',
    price: 30,
    category: 'Drinks',
    imageUrl: '/images/Menu/badam_milk.jpg',
    imageHint: 'badam milk',
  },
{
  id: '14',
  name: 'Sprite',
  description: 'A refreshing lemon-lime flavored soft drink with a crisp, clean taste.',
  price: 40,
  category: 'Drinks',
  imageUrl: '/images/Menu/sprite.jpg',
  imageHint: 'sprite soft drink',
},
{
  id: '15',
  name: 'Bovonto',
  description: 'A unique South Indian favorite with a fruity grape flavor and bubbly fizz.',
  price: 40,
  category: 'Drinks',
  imageUrl: '/images/Menu/bovontoo.jpg',
  imageHint: 'bovonto soft drink',
},
{
  id: '16',
  name: 'Coca-Cola',
  description: 'The classic cola drink loved worldwide for its bold, refreshing flavor.',
  price: 40,
  category: 'Drinks',
  imageUrl: '/images/Menu/coke.jpg',
  imageHint: 'coca cola soft drink',
},
{
  id: '17',
  name: 'Maaza',
  description: 'A delicious mango-flavored drink made with real mango pulp, sweet and smooth.',
  price: 40,
  category: 'Drinks',
  imageUrl: '/images/Menu/maazaa.jpg',
  imageHint: 'maaza mango drink',
},
  // Lunch
  {
    id: '15',
    name: 'Veg Fried Rice',
    description: 'Stir-fried rice with a mix of fresh vegetables.',
    price: 70,
    category: 'Lunch',
    imageUrl: '/images/Menu/veg_friedrice.jpg',
    imageHint: 'fried rice',
  },
  {
    id: '16',
    name: 'Paneer Fried Rice',
    description: 'Fried rice with soft paneer cubes and vegetables.',
    price: 90,
    category: 'Lunch',
    imageUrl: '/images/Menu/panner_friedrice.jpg',
    imageHint: 'paneer rice',
  },
  {
    id: '17',
    name: 'Chicken Fried Rice',
    description: 'Stir-fried rice with chicken and vegetables.',
    price: 110,
    category: 'Lunch',
    imageUrl: '/images/Menu/chicken_friedrice.jpg',
    imageHint: 'chicken rice',
  },
  {
    id: '18',
    name: 'Egg Fried Rice',
    description: 'Stir-fried rice with scrambled eggs and vegetables.',
    price: 90,
    category: 'Lunch',
    imageUrl: '/images/Menu/egg_friedrice.jpg',
    imageHint: 'egg rice',
  },
  {
    id: '19',
    name: 'Veg Biryani',
    description: 'Aromatic rice dish with mixed vegetables and spices.',
    price: 80,
    category: 'Lunch',
    imageUrl: '/images/Menu/veg_biriyani.jpg',
    imageHint: 'veg biryani',
  },
  {
    id: '20',
    name: 'Chicken Biryani',
    description: 'A rich and flavorful rice dish with spiced chicken.',
    price: 120,
    category: 'Lunch',
    imageUrl: '/images/Menu/chicken_biriyani.jpg',
    imageHint: 'chicken biryani',
  },
  {
    id: '21',
    name: 'Curd Rice',
    description: 'Comforting dish of yogurt mixed with cooked rice and spices.',
    price: 50,
    category: 'Lunch',
    imageUrl: '/images/Menu/curd_ricee.jpg',
    imageHint: 'curd rice',
  },
  {
    id: '22',
    name: 'Sambar Rice',
    description: 'A tangy and spicy rice dish made with lentils and vegetables.',
    price: 55,
    category: 'Lunch',
    imageUrl: '/images/Menu/sambar_rice.jpg',
    imageHint: 'sambar rice',
  },
  {
    id: '23',
    name: 'Lemon Rice',
    description: 'A zesty and flavorful rice dish with a lemon and peanut seasoning.',
    price: 55,
    category: 'Lunch',
    imageUrl: '/images/Menu/lemon_ricee.jpg',
    imageHint: 'lemon rice',
  },
];
